import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CDP-Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <Navbar
          menuItems={[
            "Home",
            "About Us",
            "Notices",
            "Our Team",
            "Student Login",
            "Admin Login",
            "For Recruiters",
            "Contact Us",
          ]}
        />

        <main>{children}</main>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
