import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import MainFooter from "@/components/main_footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CDP-Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <Navbar
          menuItems={[
            { label: "Home", href: "/" },
            { label: "Our Team", href: "/team" },
            { label: "For Recruiters", href: "/for_recruiters" },
            { label: "Notices", href: "/notices" },
            { label: "Student Login", href: "/student_login" },
            { label: "Admin Login", href: "/admin_login" },
          ]}
        />
        <main>{children}</main>
        {/* Footer */}
        <MainFooter />
      </body>
    </html>
  );
}
