import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <Navbar
          menuItems={[
            "Home",
            "About Us",
            "Notices",
            "Our Team",
            "Student Login",
            "Admin Login",
            "For Recruiters",
            "Contact Us",
          ]}
        />

        {/* Page Heading */}
        {/* <header style={{ textAlign: "center", padding: "20px 0" }}>
          <h1>{pageHeading}</h1>
        </header> */}

        {/* Main Content */}
        {/* <main style={{ minHeight: "70vh", padding: "20px" }}>{children}</main> */}

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
